//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Count
{
    public int ID { get; set; }
    public int AID { get; set; }
    public int number { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string name { get; set; }
    public string cate { get; set; }
}

public partial class Record
{
    public int ID { get; set; }
    public Nullable<int> AID { get; set; }
    public string IP { get; set; }
}
