//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Admin
{
    public int AdminID { get; set; }
    public string Name { get; set; }
    public string Password { get; set; }
}

public partial class Article
{
    public int ArticleID { get; set; }
    public string Title { get; set; }
    public string SubTitle { get; set; }
    public int AuthorID { get; set; }
    public string Author { get; set; }
    public string Source { get; set; }
    public string Link { get; set; }
    public string Content { get; set; }
    public string ImgUrl { get; set; }
    public string Type { get; set; }
    public bool OnTop { get; set; }
    public bool Hot { get; set; }
    public bool Attachment { get; set; }
    public System.DateTime UpdateTime { get; set; }
    public Nullable<int> Hit { get; set; }
    public Nullable<int> BelongedClub { get; set; }
    public bool Deleted { get; set; }

    public virtual User User { get; set; }
}

public partial class Connection
{
    public int ID { get; set; }
    public int GroupID { get; set; }
    public int UserID { get; set; }
    public int Class { get; set; }
    public int Right { get; set; }
    public string Job { get; set; }
    public string Duty { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }

    public virtual ITGroup ITGroup { get; set; }
    public virtual User User { get; set; }
}

public partial class Course
{
    public int CourseID { get; set; }
    public string CourseName { get; set; }
    public string Department { get; set; }
    public string Major { get; set; }
    public int Type { get; set; }
    public string Number { get; set; }
    public string EnglishName { get; set; }
    public int CourseHours { get; set; }
    public double CourseMark { get; set; }
    public Nullable<int> WeekHours { get; set; }
    public string TermArrange { get; set; }
    public Nullable<int> ExperimentHours { get; set; }
    public Nullable<double> ExperimentMark { get; set; }
    public string Textbook { get; set; }
    public string TextbookAuthor { get; set; }
    public string TextbookPublisher { get; set; }
    public string TextbookVersion { get; set; }
    public string ExperimentGuideBook { get; set; }
    public string ExperimentPlace { get; set; }
    public string CourseObject { get; set; }
    public string ExamType { get; set; }
    public string ContentAndTimeArrange { get; set; }
    public string Reference { get; set; }
    public string ExperimentPartObject { get; set; }
    public string ExperimentObject { get; set; }
}

public partial class Department
{
    public int DepartmentID { get; set; }
    public string Name { get; set; }
    public string Content { get; set; }
    public string Link { get; set; }
}

public partial class Introduce
{
    public int id { get; set; }
    public string name { get; set; }
    public string text { get; set; }
}

public partial class ITGroup
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ITGroup()
    {
        this.Connection = new HashSet<Connection>();
    }

    public int GroupID { get; set; }
    public string GroupName { get; set; }
    public int groupType { get; set; }
    public string Img { get; set; }
    public string Link { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Connection> Connection { get; set; }
}

public partial class Log
{
    public int LogID { get; set; }
    public System.DateTime Time { get; set; }
    public int Info { get; set; }
    public string IP { get; set; }
    public Nullable<int> UserID { get; set; }

    public virtual User User { get; set; }
}

public partial class Student
{
    public int StuID { get; set; }
    public string Name { get; set; }
    public int UserID { get; set; }
}

public partial class Teacher
{
    public int TeacherID { get; set; }
    public string ImgUrl { get; set; }
    public int UserID { get; set; }
    public string Name { get; set; }
    public Nullable<System.DateTime> Birthday { get; set; }
    public string PoliticsStatus { get; set; }
    public string Education { get; set; }
    public string MobilePhone { get; set; }
    public string OfficePhone { get; set; }
    public string Email { get; set; }
    public string WorkPlace { get; set; }
    public string Address { get; set; }
    public Nullable<int> JobTitle { get; set; }
    public Nullable<int> Job { get; set; }
    public Nullable<int> Tutor { get; set; }
    public string Department { get; set; }
    public string Major { get; set; }
    public string Course { get; set; }
    public string Experience { get; set; }
    public string ResearchDirection { get; set; }
    public string ResearchProject { get; set; }
    public string Achievements { get; set; }
    public string Paper { get; set; }
    public string Enrolment { get; set; }
    public string Remark { get; set; }
}

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.Article = new HashSet<Article>();
        this.Connection = new HashSet<Connection>();
        this.Log = new HashSet<Log>();
    }

    public int UserID { get; set; }
    public string Number { get; set; }
    public string Password { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Article> Article { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Connection> Connection { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Log> Log { get; set; }
}
