//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class oucITEntities : DbContext
{
    public oucITEntities()
        : base("name=oucITEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Admin> Admin { get; set; }
    public virtual DbSet<Article> Article { get; set; }
    public virtual DbSet<Connection> Connection { get; set; }
    public virtual DbSet<Course> Course { get; set; }
    public virtual DbSet<Department> Department { get; set; }
    public virtual DbSet<Introduce> Introduce { get; set; }
    public virtual DbSet<ITGroup> ITGroup { get; set; }
    public virtual DbSet<Log> Log { get; set; }
    public virtual DbSet<Student> Student { get; set; }
    public virtual DbSet<Teacher> Teacher { get; set; }
    public virtual DbSet<User> User { get; set; }
}
